// .res generated by gchimp ResMake
// https://github.com/khanghugo/gchimp
// Generated date: Fri, 17 Oct 2025 22:39:14 +0300
// models 
models/props/mw2_gulag/czero_sinkset.mdl
models/props/mw2_gulag/light_industrial.mdl
models/props/mw2_gulag/shower_set.mdl
models/props/mw2_gulag/shower_setwall.mdl
// overview
overviews/aim_gulag_showers_b2.txt
overviews/aim_gulag_showers.bmp
// sound
sound/mw2_gulag/steam_loop1.wav
sound/mw2_gulag/urb_3b_seweramb.wav
